# Generated by Django 4.0.2 on 2022-02-13 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rep_url', models.URLField(blank=True, verbose_name='Ссылка на репозиторий')),
                ('status', models.CharField(choices=[('PRC', 'В процессе'), ('DON', 'Сдан'), ('EXP', 'Просрочен'), ('CNL', 'Отменен')], default='PRC', max_length=3, verbose_name='Статус')),
                ('deadline_timestamp', models.DateTimeField(blank=True, verbose_name='Дата сдачи')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.project', verbose_name='Проект')),
            ],
        ),
    ]
