# Generated by Django 3.2.6 on 2022-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rep_url', models.URLField(blank=True, verbose_name='Ссылка на репозиторий')),
                ('status', models.CharField(choices=[('PRC', 'В процессе'), ('DON', 'Сдан'), ('EXP', 'Просрочен'), ('CNL', 'Отменен')], default='PRC', max_length=3, verbose_name='Статус')),
                ('deadline_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
