# Generated by Django 3.2.6 on 2022-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
    ]
