version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lev
      POSTGRES_PASSWORD: django
      POSTGRES_DB: todo
  backend:
    build: ./todoservice
    privileged: true
    expose:
      - "8081"
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py migrate
      && python3 manage.py fill_db 20
      && gunicorn todoservice.wsgi -b 0.0.0.0:8081
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - nginx
